[project]
name = "expected-value-router-adtech"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "drfaizyahsan",email = "dr.faizy.ahsan@gmail.com"},
]
dependencies = ["ruff==0.16.2", "mlflow==3.15.1", "pydantic==2.13", "fastapi==0.141.1", "pyspark>=4.2.0", "pytest>=9.1.1", "lightgbm>=4.7.0", "joblib>=1.5.3", "scikit-learn>=1.9.0", "pandas>=2.3.3", "numpy>=2.5.2"]
requires-python = "==3.14.*"
readme = "README.md"
license = {text = "Apache-2.0"}

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]


[tool.pdm]
distribution = false

[dependency-groups]
dev = [
    "httpx>=0.28.1",
]
